# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Epigeny
email: info@epigeny.io
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Graphic Artist - User Experience Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://epigeny.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
github_username:  epigeny
#facebook_username: StartBootstrap
#instagram_username: beyonce
stackoverflow_url: http://stackexchange.com/users/6271547/yannick-marcon
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/yannickmarcon

# Address information
address_street: 
address_city: Chamonix
address_state: France
address_zip: 

# Build settings
markdown: kramdown

theme: jekyll-theme-slate